### ISSUE TITLE
Use a prefix/sufix for namespaces created and managed by Choreo controllers.

### ISSUE THREAD

**Issue by sameerajayasoma** [choreo-idp/choreo#1]
We create a namespace for each organization in the control plane. Also, we create a namespace for every project + environment combination in the dataplane cluster. 

This suggestion will help anyone managing these clusters clearly identify the namespaces managed by Choreo. 

My suggestion for the prefix is `choreo-ns-` or `choreons-`.  Here is an example organization yaml and the generated namespace( recorded in the status section). 

```yaml
apiVersion: core.choreo.dev/v1
kind: Organization
metadata:
  creationTimestamp: "2025-02-28T19:30:18Z"
  generation: 1
  labels:
    core.choreo.dev/name: acme
  name: acme
status:
  conditions:
  - lastTransitionTime: "2025-02-28T19:30:18Z"
    message: Successfully created the Namespace
    observedGeneration: 1
    reason: NamespaceCreated
    status: "True"
    type: Ready
  namespace: choreo-ns-acme
  observedGeneration: 1
```

**Comment by Mirage20** [comment]
IMO, we should avoid prefixing the controller-generated resources and use labels (like `managed-by`) so that users can identify the managed namespaces clearly. This is both human and machine-friendly. Users can list the Choreo managed namespaces like this ` kubectl get ns -l managed-by=choreo-control-plane`.

This behavior will be similar to other k8s controllers like Deployment and StatefulSet where the Pods created by these controllers won't have information about who is managing it in the name. WDYT?

**Comment by sameerajayasoma** [comment]
+1 for having managed-by labels for things that Choreo creates. 

But, having prefixes solves a different problem. They give a clear visual indication for anyone probing into the K8s cluster and avoid conflicts to a certain degree. We could even have a `choreons-default` as the namespace created for the `default` org.

**Comment by Mirage20** [comment]
Yes, I agree. It directly shows the namespaces that are created by Choreo in the control plane, so that users can use grep-like tools to identify the namespaces. But, I think modifying the name of the namespaces will remove the control from the user to give nice and clean names. It also impacts the YAMLs committed to the GitOps. For example, consider the following Organization and Project,

```yaml
apiVersion: core.choreo.dev/v1
kind: Organization
metadata:
  name: acme
  annotations:
    core.choreo.dev/display-name: Acme Organization
    core.choreo.dev/description: Choreo Organization for Acme
  labels:
    core.choreo.dev/name: acme
spec: {}
---

apiVersion: core.choreo.dev/v1
kind: Project
metadata:
  name: project-1
  namespace: acme                            <------ user has to now give this as choreons-acme instead of acme
  annotations:
    core.choreo.dev/display-name: Test Project
    core.choreo.dev/description: Test project for acme
  labels:
    core.choreo.dev/organization: acme      <------- Here user gives acme.
    core.choreo.dev/name: project-1
spec:
  deploymentPipelineRef: default-pipeline

```

Here, in Project YAML, the user has to give the correct namespace with the prefix, which I think is bad because users need to be aware of our prefixing and ensure it is added correctly to all the namespace resources. To me, this feels like an extra effort for the user to maintain the GitOps repository.
